// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgsfNUpLHZSfA10r6wU-Aim4LcefImjTE',
    appId: '1:468167045229:web:dc9085b36e6d1e92058f64',
    messagingSenderId: '468167045229',
    projectId: 'gotogether-eb576',
    authDomain: 'gotogether-eb576.firebaseapp.com',
    storageBucket: 'gotogether-eb576.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB35ar_qa5oau055oyKkvLdonz-R4KebDI',
    appId: '1:468167045229:android:146fad509878fc44058f64',
    messagingSenderId: '468167045229',
    projectId: 'gotogether-eb576',
    storageBucket: 'gotogether-eb576.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7NXeFFhZGN4c13xc7rhHeYYHRV02XmfY',
    appId: '1:468167045229:ios:2a0f12d9f70852a7058f64',
    messagingSenderId: '468167045229',
    projectId: 'gotogether-eb576',
    storageBucket: 'gotogether-eb576.appspot.com',
    iosBundleId: 'com.example.almostZenly',
  );
}
